{"variants":[{"paths":["\/documentation\/chatroomuikit\/chatbarragelist\/ichatbarragelistdriver-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatbarragelist\/ichatbarragelistdriver-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/IChatBarrageListDriver-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/refreshMessage(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/removeMessage(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/showNewMessage(message:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"IChatBarrageListDriver Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/removeMessage(message:)":{"role":"symbol","title":"removeMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description When you want delete message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/removeMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeMessageWithMessage:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/removemessage(message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/showNewMessage(message:)":{"role":"symbol","title":"showNewMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNewMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description When you receive or will send a message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/showNewMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showNewMessageWithMessage:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/shownewmessage(message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList/refreshMessage(message:)":{"role":"symbol","title":"refreshMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13ChatroomUIKit11ChatMessagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description When you want modify or translate a message."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/refreshMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshMessageWithMessage:"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist\/refreshmessage(message:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageList":{"role":"symbol","title":"ChatBarrageList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBarrageList"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBarrageList"}],"url":"\/documentation\/chatroomuikit\/chatbarragelist"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/refreshMessage(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/removeMessage(message:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageList\/showNewMessage(message:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1removeMessage(message:)\/title","value":"removeMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1removeMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeMessageWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1showNewMessage(message:)\/title","value":"showNewMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1showNewMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewMessageWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1refreshMessage(message:)\/title","value":"refreshMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList~1refreshMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshMessageWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList\/title","value":"ChatBarrageList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageList\/fragments","value":[{"kind":"identifier","text":"ChatBarrageList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}