{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitInitialOptions","text":"RoomUIKitInitialOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/option"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/option"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/option","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitInitialOptions"}],"title":"option","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitClient(py)option","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"option"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient":{"role":"symbol","title":"RoomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomUIKitClient"}],"abstract":[{"type":"text","text":"Description ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/option":{"role":"symbol","title":"option","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitInitialOptions"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/option","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"option"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/option"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitInitialOptions":{"role":"symbol","title":"RoomUIKitInitialOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomUIKitInitialOptions"}],"abstract":[{"type":"text","text":"Description A wrapper class for some options when initializing ChatroomUIKit.ChatroomView."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitInitialOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomUIKitInitialOptions"}],"url":"\/documentation\/chatroomuikit\/roomuikitinitialoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"option"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"option"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitInitialOptions","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitInitialOptions","text":"RoomUIKitInitialOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"option"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/title","value":"RoomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/fragments","value":[{"kind":"identifier","text":"RoomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1option\/title","value":"option"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1option\/fragments","value":[{"kind":"identifier","text":"option"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitInitialOptions\/title","value":"RoomUIKitInitialOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitInitialOptions\/fragments","value":[{"kind":"identifier","text":"RoomUIKitInitialOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}