{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerRoomEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener","text":"RoomEventsListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/registerroomeventslistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/registerroomeventslistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/registerRoomEventsListener(listener:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerRoomEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"title":"registerRoomEventsListener(listener:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)RoomUIKitClient(im)registerRoomEventsListenerWithListener:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/registerRoomEventsListener(listener:)":{"role":"symbol","title":"registerRoomEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerRoomEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomEventsListener","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/registerRoomEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/registerroomeventslistener(listener:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomEventsListener":{"role":"symbol","title":"RoomEventsListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomEventsListener"}],"abstract":[{"type":"text","text":"Description All events listener of chatroom."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomEventsListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomEventsListener"}],"url":"\/documentation\/chatroomuikit\/roomeventslistener"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient":{"role":"symbol","title":"RoomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomUIKitClient"}],"abstract":[{"type":"text","text":"Description ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerRoomEventsListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<RoomEventsListener>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)RoomEventsListener"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1registerRoomEventsListener(listener:)\/title","value":"registerRoomEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1registerRoomEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerRoomEventsListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener\/title","value":"RoomEventsListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomEventsListener\/fragments","value":[{"kind":"identifier","text":"RoomEventsListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/title","value":"RoomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/fragments","value":[{"kind":"identifier","text":"RoomUIKitClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}