{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity","text":"ChatEntity"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"chat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"实体对象"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/chatbarragecell\/refresh(chat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/chatbarragecell\/refresh(chat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageCell\/refresh(chat:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Description 刷新渲染聊天弹幕的实体，内部包含高度宽度以及富文本缓存"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity"},{"kind":"text","text":")"}],"title":"refresh(chat:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)ChatBarrageCell(im)refreshWithChat:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"refreshWithChat:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageCell"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageCell":{"role":"symbol","title":"ChatBarrageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatBarrageCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatBarrageCell"}],"url":"\/documentation\/chatroomuikit\/chatbarragecell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatBarrageCell/refresh(chat:)":{"role":"symbol","title":"refresh(chat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description 刷新渲染聊天弹幕的实体，内部包含高度宽度以及富文本缓存"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatBarrageCell\/refresh(chat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshWithChat:"}],"url":"\/documentation\/chatroomuikit\/chatbarragecell\/refresh(chat:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ChatEntity":{"role":"symbol","title":"ChatEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEntity"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatEntity"}],"url":"\/documentation\/chatroomuikit\/chatentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshWithChat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithChat:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshWithChat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ChatEntity","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatEntity","text":"ChatEntity"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"chat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageCell\/title","value":"ChatBarrageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageCell\/fragments","value":[{"kind":"identifier","text":"ChatBarrageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageCell~1refresh(chat:)\/title","value":"refreshWithChat:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatBarrageCell~1refresh(chat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithChat:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEntity\/title","value":"ChatEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ChatEntity\/fragments","value":[{"kind":"identifier","text":"ChatEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}