{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/componentsregister"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/componentsregister"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftBarragesViewCell","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftsCell","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/InputBar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/barrageStyle"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/shared"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"title":"ComponentsRegister","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)ComponentsRegister","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/barrageStyle":{"role":"symbol","title":"barrageStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barrageStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatBarrageCellStyle","preciseIdentifier":"c:@M@ChatroomUIKit@E@ChatBarrageCellStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/barrageStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barrageStyle"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/barragestyle"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/InputBar":{"role":"symbol","title":"InputBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatInputBar","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ChatInputBar"},{"kind":"text","text":".Type"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/InputBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputBar"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/inputbar"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/init"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentsRegister","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)ComponentsRegister"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/shared"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/GiftsCell":{"role":"symbol","title":"GiftsCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftEntityCell"},{"kind":"text","text":".Type"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftsCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsCell"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/giftscell"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister/GiftBarragesViewCell":{"role":"symbol","title":"GiftBarragesViewCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftBarragesViewCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftBarrageCell","preciseIdentifier":"c:@M@ChatroomUIKit@objc(cs)GiftBarrageCell"},{"kind":"text","text":".Type"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftBarragesViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftBarragesViewCell"}],"url":"\/documentation\/chatroomuikit\/componentsregister\/giftbarragesviewcell"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/chatroomuikit\/componentsregister"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftBarragesViewCell","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/GiftsCell","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/InputBar","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/barrageStyle"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/ComponentsRegister\/shared"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1barrageStyle\/title","value":"barrageStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1barrageStyle\/fragments","value":[{"kind":"identifier","text":"barrageStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1InputBar\/title","value":"InputBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1InputBar\/fragments","value":[{"kind":"identifier","text":"InputBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftsCell\/title","value":"GiftsCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftsCell\/fragments","value":[{"kind":"identifier","text":"GiftsCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftBarragesViewCell\/title","value":"GiftBarragesViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister~1GiftBarragesViewCell\/fragments","value":[{"kind":"identifier","text":"GiftBarragesViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}