{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftserviceimplement"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftService","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)EMChatManagerDelegate","doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChatroomUIKit\/SQ","doc:\/\/org.cocoapods.ChatroomUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/init(roomId:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/EMChatManagerDelegate-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"title":"GiftServiceImplement","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatroomUIKit@objc(cs)GiftServiceImplement","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement":{"role":"symbol","title":"GiftServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftServiceImplement"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/init(roomId:)":{"role":"symbol","title":"init(roomId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/init(roomId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRoomId:"}],"url":"\/documentation\/chatroomuikit\/giftserviceimplement\/init(roomid:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SQ"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)EMChatManagerDelegate":{"type":"unresolvable","title":"HyphenateChat.EMChatManagerDelegate","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)EMChatManagerDelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/GiftService-Implementations":{"role":"collectionGroup","title":"GiftService Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/giftserviceimplement\/giftservice-implementations"},"doc://org.cocoapods.ChatroomUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ChatroomUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChatroomUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/s7CVarArgP"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftService":{"role":"symbol","title":"GiftService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftService"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftService"}],"url":"\/documentation\/chatroomuikit\/giftservice"},"doc://org.cocoapods.ChatroomUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/SH"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftServiceImplement/EMChatManagerDelegate-Implementations":{"role":"collectionGroup","title":"EMChatManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/EMChatManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatroomuikit\/giftserviceimplement\/emchatmanagerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/init(roomId:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/EMChatManagerDelegate-Implementations","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftServiceImplement\/GiftService-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftServiceImplement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/title","value":"GiftServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement\/fragments","value":[{"kind":"identifier","text":"GiftServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1init(roomId:)\/title","value":"initWithRoomId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftServiceImplement~1init(roomId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRoomId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftService\/title","value":"GiftService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftService\/fragments","value":[{"kind":"identifier","text":"GiftService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}