{"variants":[{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/userstatechangedlistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomuikitclient\/userstatechangedlistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/UserStateChangedListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenWillExpired()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ChatroomUIKit"}],"role":"collectionGroup","title":"UserStateChangedListener Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/onUserTokenWillExpired()":{"role":"symbol","title":"onUserTokenWillExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenWillExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Description User token will expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenWillExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenWillExpired"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/onusertokenwillexpired()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/onSocketConnectionStateChanged(state:)":{"role":"symbol","title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionState","preciseIdentifier":"s:13ChatroomUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description Chatroom socket connection state changed listener."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onSocketConnectionStateChanged(state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/onsocketconnectionstatechanged(state:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient":{"role":"symbol","title":"RoomUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomUIKitClient"}],"abstract":[{"type":"text","text":"Description ChatroomUIKit initialize class."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomUIKitClient"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/onUserTokenDidExpired()":{"role":"symbol","title":"onUserTokenDidExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTokenDidExpired"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Description User token expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenDidExpired()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/onusertokendidexpired()"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomUIKitClient/onUserLoginOtherDevice(device:)":{"role":"symbol","title":"onUserLoginOtherDevice(device:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Description User login at other device"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserLoginOtherDevice(device:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"url":"\/documentation\/chatroomuikit\/roomuikitclient\/onuserloginotherdevice(device:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomUIKitClient\/onUserTokenWillExpired()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserTokenWillExpired()\/title","value":"onUserTokenWillExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserTokenWillExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenWillExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onSocketConnectionStateChanged(state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/title","value":"RoomUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient\/fragments","value":[{"kind":"identifier","text":"RoomUIKitClient"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserTokenDidExpired()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomUIKitClient~1onUserLoginOtherDevice(device:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}