{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gifts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol","text":"GiftEntityProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftToChannelResultDelegate","text":"GiftToChannelResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate","text":"GiftsViewActionEventsDelegate"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/giftsviewcontroller\/init(gifts:result:eventsdelegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/giftsviewcontroller\/init(gifts:result:eventsdelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/init(gifts:result:eventsDelegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gifts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftToChannelResultDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftToChannelResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":"?)"}],"title":"init(gifts:result:eventsDelegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ChatroomUIKit@objc(cs)GiftsViewController(im)initWithGifts:result:eventsDelegate:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithGifts:result:eventsDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewActionEventsDelegate":{"role":"symbol","title":"GiftsViewActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}],"url":"\/documentation\/chatroomuikit\/giftsviewactioneventsdelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftEntityProtocol":{"role":"symbol","title":"GiftEntityProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftEntityProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftEntityProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftEntityProtocol"}],"url":"\/documentation\/chatroomuikit\/giftentityprotocol"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController/init(gifts:result:eventsDelegate:)":{"role":"symbol","title":"init(gifts:result:eventsDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gifts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftToChannelResultDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftToChannelResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftsViewActionEventsDelegate","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController\/init(gifts:result:eventsDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithGifts:result:eventsDelegate:"}],"url":"\/documentation\/chatroomuikit\/giftsviewcontroller\/init(gifts:result:eventsdelegate:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftsViewController":{"role":"symbol","title":"GiftsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftsViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftsViewController"}],"url":"\/documentation\/chatroomuikit\/giftsviewcontroller"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftToChannelResultDelegate":{"role":"symbol","title":"GiftToChannelResultDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftToChannelResultDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}],"url":"\/documentation\/chatroomuikit\/gifttochannelresultdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithGifts:result:eventsDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGifts:result:eventsDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGifts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<GiftEntityProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gifts"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftToChannelResultDelegate>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftToChannelResultDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventsDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GiftsViewActionEventsDelegate>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)GiftsViewActionEventsDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"eventsDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/title","value":"GiftsViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"GiftsViewActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/title","value":"GiftEntityProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftEntityProtocol\/fragments","value":[{"kind":"identifier","text":"GiftEntityProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController~1init(gifts:result:eventsDelegate:)\/title","value":"initWithGifts:result:eventsDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController~1init(gifts:result:eventsDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGifts:result:eventsDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/title","value":"GiftsViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftsViewController\/fragments","value":[{"kind":"identifier","text":"GiftsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate\/title","value":"GiftToChannelResultDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate\/fragments","value":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}