{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftToChannelResultDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/gifttochannelresultdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/gifttochannelresultdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate\/giftResult(gift:error:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftToChannelResultDelegate"}],"title":"GiftToChannelResultDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChatroomUIKit@objc(pl)GiftToChannelResultDelegate","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftToChannelResultDelegate/giftResult(gift:error:)":{"navigatorTitle":[{"kind":"identifier","text":"giftResultWithGift:error:"}],"role":"symbol","title":"giftResult(gift:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"giftResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GiftEntityProtocol","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)GiftEntityProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13ChatroomUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate\/giftResult(gift:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chatroomuikit\/gifttochannelresultdelegate\/giftresult(gift:error:)"},"doc://org.cocoapods.ChatroomUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/GiftToChannelResultDelegate":{"role":"symbol","title":"GiftToChannelResultDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftToChannelResultDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}],"url":"\/documentation\/chatroomuikit\/gifttochannelresultdelegate"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GiftToChannelResultDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/GiftToChannelResultDelegate\/giftResult(gift:error:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChatroomUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GiftToChannelResultDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate~1giftResult(gift:error:)\/title","value":"giftResultWithGift:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate~1giftResult(gift:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"giftResultWithGift:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate\/title","value":"GiftToChannelResultDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1GiftToChannelResultDelegate\/fragments","value":[{"kind":"identifier","text":"GiftToChannelResultDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}