{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftDriver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IGiftsBarrageListDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDriver","text":"IGiftsBarrageListDriver"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomservice\/bindgiftdriver(driver:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatroomuikit\/roomservice\/bindgiftdriver(driver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/bindGiftDriver(driver:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftDriver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGiftsBarrageListDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDriver"},{"kind":"text","text":")"}],"title":"bindGiftDriver(driver:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChatroomUIKit@objc(cs)RoomService(im)bindGiftDriverWithDriver:","modules":[{"name":"ChatroomUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bindGiftDriverWithDriver:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Description Chat room hub service transfer class in chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IGiftsBarrageListDriver":{"role":"symbol","title":"IGiftsBarrageListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IGiftsBarrageListDriver"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IGiftsBarrageListDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IGiftsBarrageListDriver"}],"url":"\/documentation\/chatroomuikit\/igiftsbarragelistdriver"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/bindGiftDriver(driver:)":{"role":"symbol","title":"bindGiftDriver(driver:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGiftDriver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IGiftsBarrageListDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDriver"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/bindGiftDriver(driver:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindGiftDriverWithDriver:"}],"url":"\/documentation\/chatroomuikit\/roomservice\/bindgiftdriver(driver:)"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bindGiftDriverWithDriver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindGiftDriverWithDriver:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindGiftDriverWithDriver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<IGiftsBarrageListDriver>","preciseIdentifier":"c:Qo@M@ChatroomUIKit@objc(pl)IGiftsBarrageListDriver"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"driver"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IGiftsBarrageListDriver\/title","value":"IGiftsBarrageListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IGiftsBarrageListDriver\/fragments","value":[{"kind":"identifier","text":"IGiftsBarrageListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1bindGiftDriver(driver:)\/title","value":"bindGiftDriverWithDriver:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService~1bindGiftDriver(driver:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindGiftDriverWithDriver:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}